export const MockList = [
  {
    contributions_count: 84,
    dependent_repos_count: 386381,
    dependents_count: 41780,
    deprecation_reason: null,
    description: 'The JavaScript Task Runner',
    forks: 1536,
    homepage: 'https://gruntjs.com/',
    keywords: [
      'task',
      'async',
      'cli',
      'minify',
      'uglify',
      'build',
      'lodash',
      'unit',
      'test',
      'qunit',
      'nodeunit',
      'server',
      'init',
      'scaffold',
      'make',
      'jake',
      'tool',
      'hacktoberfest',
    ],
    language: 'JavaScript',
    latest_download_url: 'https://registry.npmjs.org/grunt/-/grunt-1.6.1.tgz',
    latest_release_number: '1.6.1',
    latest_release_published_at: '2023-01-31T15:11:06.534Z',
    latest_stable_release_number: '1.6.1',
    latest_stable_release_published_at: '2023-01-31T15:11:06.534Z',
    license_normalized: false,
    licenses: 'MIT',
    name: 'grunt',
    normalized_licenses: ['MIT'],
    package_manager_url: 'https://www.npmjs.com/package/grunt',
    platform: 'NPM',
    rank: 29,
    repository_license: 'Other',
    repository_status: null,
    repository_url: 'https://github.com/gruntjs/grunt',
    stars: 12193,
    status: null,
    versions: [
      {
        number: '1.2.1',
        published_at: '2020-07-07T14:27:55.762Z',
        spdx_expression: 'MIT',
        original_license: 'MIT',
        researched_at: null,
        repository_sources: ['NPM'],
      },
      {
        number: '0.1.0',
        published_at: '2012-01-12T13:08:51.911Z',
        spdx_expression: 'MIT',
        original_license: 'MIT',
        researched_at: null,
        repository_sources: ['NPM'],
      },
      {
        number: '0.4.0-rc4',
        published_at: '2012-12-17T22:17:51.260Z',
        spdx_expression: 'MIT',
        original_license: 'MIT',
        researched_at: null,
        repository_sources: ['NPM'],
      },
      {
        number: '1.0.2',
        published_at: '2018-02-07T21:43:31.858Z',
        spdx_expression: 'MIT',
        original_license: 'MIT',
        researched_at: null,
        repository_sources: ['NPM'],
      },
      {
        number: '1.1.0',
        published_at: '2020-03-17T02:37:19.588Z',
        spdx_expression: 'MIT',
        original_license: 'MIT',
        researched_at: null,
        repository_sources: ['NPM'],
      },
    ],
  },
  {
    contributions_count: 46,
    dependent_repos_count: 59517,
    dependents_count: 3255,
    deprecation_reason: null,
    description: 'grunt plugin for karma test runner',
    forks: 127,
    homepage: 'https://github.com/karma-runner/grunt-karma#readme',
    keywords: ['gruntplugin', 'karma', 'grunt', 'test', 'unit', 'runner', 'TDD'],
    language: 'JavaScript',
    latest_download_url: 'https://registry.npmjs.org/grunt-karma/-/grunt-karma-4.0.2.tgz',
    latest_release_number: '4.0.2',
    latest_release_published_at: '2021-05-11T23:46:36.597Z',
    latest_stable_release_number: '4.0.2',
    latest_stable_release_published_at: '2021-05-11T23:46:36.597Z',
    license_normalized: false,
    licenses: 'MIT',
    name: 'grunt-karma',
    normalized_licenses: ['MIT'],
    package_manager_url: 'https://www.npmjs.com/package/grunt-karma',
    platform: 'NPM',
    rank: 26,
    repository_license: 'MIT',
    repository_status: null,
    repository_url: 'https://github.com/karma-runner/grunt-karma',
    stars: 471,
    status: null,
    versions: [
      {
        number: '0.3.0',
        published_at: '2013-03-19T19:18:31.208Z',
        spdx_expression: 'MIT',
        original_license: 'MIT',
        researched_at: null,
        repository_sources: ['NPM'],
      },
      {
        number: '0.10.0',
        published_at: '2015-01-09T00:40:45.540Z',
        spdx_expression: 'MIT',
        original_license: 'MIT',
        researched_at: null,
        repository_sources: ['NPM'],
      },
      {
        number: '0.10.1',
        published_at: '2015-01-09T10:28:04.032Z',
        spdx_expression: 'MIT',
        original_license: 'MIT',
        researched_at: null,
        repository_sources: ['NPM'],
      },
    ],
  },
];
